### ISSUE TITLE
Problems running barcode_correct_sciatac.py on the test dataset

### ISSUE THREAD

**Issue by cflerin** [shendurelab/human-atac#1]
Hi, I'm trying to run the `barcode_correct_sciatac.py` script on the test data as described here in the main readme:

> Script testing
In addition, we provide small test fastqs (Undetermined_R1_for_test.fastq.gz and Undetermined_R2_for_test.fastq.gz) which allow you to test the demux script on a smaller subset of 100000 reads (the appropriate samplesheet for these files is provided as samplesheet_test_demux.txt).

I'm running the following command:
```
$ python barcode_correct_sciatac.py \
>   --samplesheet samplesheets/samplesheet_test_demux.txt \
>   -1 <(cat test_data/Undetermined_R1_for_test.fastq.gz) \
>   -2 <(cat test_data/Undetermined_R2_for_test.fastq.gz) \
>   --output1_prefix r1. \
>   --output2_prefix r2. \
>   --stats_out test_out_json \
>   --wells_384
Traceback (most recent call last):
  File "barcode_correct_sciatac.py", line 599, in <module>
    raise ValueError('Warning, you had less than 5 percent of all reads pass index correction. Something may have gone wrong here w.r.t. index sets or the expected library configuration not matching the data...')
ValueError: Warning, you had less than 5 percent of all reads pass index correction. Something may have gone wrong here w.r.t. index sets or the expected library configuration not matching the data...
```

Am I doing something wrong here? The output json file is:
```
{
    "pcr_i5": 0.0013,
    "pcr_i7": 0.93147,
    "tagmentation_i5": 0.00474,
    "tagmentation_i7": 0.95688,
    "all_barcodes": 4e-05,
    "total_input_reads": 100000,
    "total_not_specified_in_samplesheet": 0
}
```

Another note is that the test data here doesn't appear to be actually gzipped, so I had to use cat instead.

Thanks for any help you can provide!

**Comment by francat** [comment]
Hi there,
I'm having the same problem when running the script on the test data and on the sample_36_brain fastq files I downloaded from the GEO. Any advice on how to proceed? 
Thanks a lot! 
Fran

**Comment by domcke** [comment]
You need to add the -X flag for the test data since the data is in the Nextseq format. The data on dbGaP is already split by sample, so you shouldn't need to run this script.
