### ISSUE TITLE
Marker gene data location

### ISSUE THREAD

**Issue by cynthier** [shendurelab/human-atac#2]
Hi, dear authors,  thank you for your great job, could you please tell me how can I get the marker gene data you used in the paper?  I can not find it in supplementary data.

**Comment by domcke** [comment]
Hi, Can you specify which marker gene data you are referring to? One exemplary marker gene per cell type is shown in Figure S3A (derived from the literature). I can send you an extended list, if these are the marker genes you are referring to.

**Comment by cynthier** [comment]
Thank you for your reply, I need all the marker information you used to identity the celltypes in 15 organs. I found some similar information on the website&nbsp;https://descartes.brotmanbaty.org/bbi/human-gene-expression-during-development/&nbsp; "Garnett Cell Type Classifiers"&nbsp;&nbsp;part, but I am not sure whether it contains all the marker gene imforation that you can provide.










LM.2Y
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shendurelab/human-atac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shendurelab/human-atac] Marker gene data location (Issue #2)





 
Hi, Can you specify which marker gene data you are referring to? One exemplary marker gene per cell type is shown in Figure S3A (derived from the literature). I can send you an extended list, if these are the marker genes you are referring to.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by domcke** [comment]
Please contact me via email and I can send you a list.
